import os
import json
import datetime
from typing import Optional, List
from fastapi import APIRouter, Depends, HTTPException, status, Query
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from app.config import settings
from app.database import get_db
from app.models.models import Patient, PrescriptionReview, User
from app.schemas.schemas import (
    PrescriptionGenerateRequest,
    PrescriptionGenerateResponse,
    DeliveryRequest,
    DeliveryResponse,
    PrescriptionReviewResponse
)
from app.security.auth_handler import get_current_user, require_roles
from app.security.anonymizer import log_audit_event, extract_clinical_payload
from app.services.pdf_service import pdf_service
from app.services.delivery_service import delivery_service

router = APIRouter(prefix="/prescription", tags=["Prescription & PDF Generator"])

@router.post("/generate", response_model=PrescriptionGenerateResponse)
def generate_prescription(
    payload: PrescriptionGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_roles(["doctor", "admin"]))
):
    """
    Tier 2 -> Tier 3: E-Prescription & ReportLab PDF Generation
    - Requires mandatory clinician review & verification
    - Includes pseudo-anonymized Patient ID, diagnosis, clinical notes,
      verified medications, chronopharmacology timetable, and disclaimer
    - Transitions Patient status to PRESCRIPTION_GENERATED
    """
    if not payload.is_verified:
        raise HTTPException(
            status_code=400,
            detail="Prescription orders cannot be generated without explicit clinician verification."
        )

    patient = db.query(Patient).filter(Patient.patient_id == payload.patient_id).first()
    patient_vitals = {}
    if patient:
        p_payload = extract_clinical_payload(patient)
        patient_vitals = {
            "age": p_payload["age"],
            "weight": p_payload["weight_kg"],
            "height": p_payload["height_cm"],
            "gender": p_payload["gender"],
            "bsa": p_payload["bsa_m2"],
            "bmi": p_payload["bmi"],
            "allergies": p_payload["allergies"],
            "medical_history": p_payload["medical_history"]
        }

    # Generate the PDF with primary diagnosis and clinician details
    pdf_res = pdf_service.generate_prescription_pdf(
        patient_id=payload.patient_id,
        doctor_name=payload.doctor_name or current_user.full_name,
        clinic_name=payload.clinic_name or "ChronoRx Health Network",
        confirmed_medications=payload.confirmed_medications,
        patient_vitals=patient_vitals,
        schedule=payload.schedule,
        interaction_warnings=payload.interaction_warnings,
        dietary_instructions=payload.dietary_instructions,
        ocr_summary=payload.ocr_summary,
        clinician_notes=payload.clinician_notes,
        diagnosis=payload.diagnosis or (patient.diagnosis if patient else None),
        is_verified=payload.is_verified,
        reviewed_by=payload.reviewed_by or current_user.full_name
    )

    # Record review in database
    review_record = PrescriptionReview(
        review_id=pdf_res["review_id"],
        patient_id=payload.patient_id,
        doctor_id=current_user.user_id,
        doctor_name=current_user.full_name,
        diagnosis=payload.diagnosis or (patient.diagnosis if patient else ""),
        medications=json.dumps(payload.confirmed_medications),
        interactions=json.dumps(payload.interaction_warnings or []),
        schedule=json.dumps(payload.schedule or []),
        clinician_notes=payload.clinician_notes or "",
        is_reviewed=payload.is_verified,
        reviewed_by=payload.reviewed_by or current_user.full_name,
        reviewed_at=datetime.datetime.utcnow(),
        pdf_path=pdf_res["pdf_url"],
        delivery_status="NOT_SENT"
    )
    db.add(review_record)

    # Transition patient status to PRESCRIPTION_GENERATED
    if patient:
        patient.status = "PRESCRIPTION_GENERATED"
        patient.consultation_completed_at = datetime.datetime.utcnow()
        if payload.diagnosis:
            patient.diagnosis = payload.diagnosis

    db.commit()

    log_audit_event(
        db,
        patient_id=payload.patient_id,
        user_id=current_user.user_id,
        action="PRESCRIPTION_GENERATED",
        details=f"E-Prescription PDF generated by {current_user.full_name} ({current_user.user_id}): {pdf_res['pdf_filename']} (Verification: Verified & Signed)"
    )

    # Automatically create a 3-day post-consultation follow-up communication window
    from app.api.followups import create_or_get_followup_session
    create_or_get_followup_session(
        db=db,
        patient_id=payload.patient_id,
        doctor_id=current_user.user_id,
        doctor_name=current_user.full_name,
        review_id=review_record.review_id,
        diagnosis=review_record.diagnosis,
        billing_reference=f"BILL-{review_record.review_id}",
        billed_at=review_record.reviewed_at,
        audit_user_id=current_user.user_id,
    )

    return pdf_res

@router.post("/deliver", response_model=DeliveryResponse)
def deliver_prescription(
    payload: DeliveryRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Tier 3: Patient Prescription Delivery (WhatsApp / SMS)
    Dispatches prescription via configured digital gateway or gracefully returns
    'Digital delivery service is not configured' fallback without crashing.
    """
    if current_user.role == "patient":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access forbidden: Patients cannot dispatch prescriptions."
        )

    patient = db.query(Patient).filter(Patient.patient_id == payload.patient_id).first()
    phone_to_use = payload.phone or (patient.phone if patient else None)

    # Fetch review record if review_id given or get latest for patient
    review = None
    if payload.review_id:
        review = db.query(PrescriptionReview).filter(PrescriptionReview.review_id == payload.review_id).first()
    if not review:
        review = db.query(PrescriptionReview).filter(
            PrescriptionReview.patient_id == payload.patient_id
        ).order_by(PrescriptionReview.id.desc()).first()

    pdf_url = review.pdf_path if review else f"/reports/ChronoRx_{payload.patient_id}_latest.pdf"

    # Call delivery service abstraction
    delivery_result = delivery_service.send_prescription(
        patient_id=payload.patient_id,
        phone_number=phone_to_use,
        pdf_url=pdf_url,
        delivery_channel=payload.delivery_channel,
        patient_name=patient.name if patient else None
    )

    if review:
        review.delivery_status = delivery_result["status"]
        review.delivery_details = delivery_result["message"]
        db.commit()

    # Audit logging
    log_action = "PRESCRIPTION_SENT" if delivery_result["success"] else "PRESCRIPTION_DELIVERY_ATTEMPTED"
    log_audit_event(
        db,
        patient_id=payload.patient_id,
        user_id=current_user.user_id,
        action=log_action,
        details=f"Delivery via {payload.delivery_channel.upper()} attempted by {current_user.user_id}. Status: {delivery_result['status']}."
    )

    return DeliveryResponse(
        success=delivery_result["success"],
        status=delivery_result["status"],
        message=delivery_result["message"],
        delivery_channel=delivery_result["delivery_channel"],
        destination=delivery_result.get("destination"),
        timestamp=delivery_result["timestamp"]
    )

@router.post("/log-download")
def log_prescription_download(
    patient_id: str,
    review_id: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Logs prescription PDF download event for compliance audit."""
    if current_user.role == "patient" and current_user.patient_id != patient_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access forbidden: Patients may only access their own prescription logs."
        )

    log_audit_event(
        db,
        patient_id=patient_id,
        user_id=current_user.user_id,
        action="PRESCRIPTION_DOWNLOADED",
        details=f"Prescription PDF downloaded for patient {patient_id} (Ref: {review_id or 'Latest'})."
    )
    return {"status": "logged"}

@router.post("/log-print")
def log_prescription_print(
    patient_id: str,
    review_id: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Logs prescription browser print event for compliance audit."""
    if current_user.role == "patient" and current_user.patient_id != patient_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access forbidden: Patients may only access their own prescription logs."
        )

    log_audit_event(
        db,
        patient_id=patient_id,
        user_id=current_user.user_id,
        action="PRESCRIPTION_PRINTED",
        details=f"Prescription browser print invoked for patient {patient_id} (Ref: {review_id or 'Latest'})."
    )
    return {"status": "logged"}

prescriptions_router = APIRouter(prefix="/prescriptions", tags=["Prescription History"])

@prescriptions_router.get("/{review_id}/download")
@router.get("/{review_id}/download")
def download_prescription_pdf(
    review_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Secure download endpoint for Prescription PDF:
    - Enforces IDOR protection: Patients can only download their own prescription PDF
    - Validates prescription review existence
    - Logs audit event
    - Returns FileResponse
    """
    review = db.query(PrescriptionReview).filter(PrescriptionReview.review_id == review_id).first()
    if not review:
        raise HTTPException(status_code=404, detail=f"Prescription review '{review_id}' not found.")

    if current_user.role == "patient":
        if current_user.patient_id != review.patient_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Access forbidden: Patients may only download their own prescription PDF."
            )
        if not review.is_reviewed or review.status != "ACTIVE":
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Access forbidden: Unverified or inactive prescriptions cannot be downloaded."
            )

    pdf_filename = f"ChronoRx_{review.patient_id}_{review.review_id}.pdf"
    pdf_path = os.path.join(settings.GENERATED_REPORTS_DIR, pdf_filename)
    if not os.path.exists(pdf_path):
        if review.pdf_path and os.path.exists(review.pdf_path):
            pdf_path = review.pdf_path
        else:
            raise HTTPException(status_code=404, detail="Prescription PDF file not found on server.")

    log_audit_event(
        db,
        patient_id=review.patient_id,
        user_id=current_user.user_id,
        action="PRESCRIPTION_DOWNLOADED",
        details=f"Prescription PDF {pdf_filename} downloaded by {current_user.user_id} ({current_user.role})."
    )

    return FileResponse(
        path=pdf_path,
        filename=pdf_filename,
        media_type="application/pdf"
    )

@prescriptions_router.get("/{patient_id}", response_model=List[PrescriptionReviewResponse])
@router.get("/patient/{patient_id}", response_model=List[PrescriptionReviewResponse])
def get_patient_prescriptions(
    patient_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Retrieves all generated prescriptions for a given patient."""
    if current_user.role == "patient":
        if current_user.patient_id != patient_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Access forbidden: Patients may only access their own prescriptions."
            )
        reviews = db.query(PrescriptionReview).filter(
            PrescriptionReview.patient_id == patient_id,
            PrescriptionReview.is_reviewed == True,
            PrescriptionReview.status == "ACTIVE"
        ).order_by(PrescriptionReview.created_at.desc()).all()
        return reviews

    reviews = db.query(PrescriptionReview).filter(
        PrescriptionReview.patient_id == patient_id
    ).order_by(PrescriptionReview.created_at.desc()).all()
    return reviews

@prescriptions_router.post("/{prescription_id}/send", response_model=DeliveryResponse)
def send_prescription_by_id(
    prescription_id: str,
    phone: Optional[str] = None,
    channel: str = "whatsapp",
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Tier 3: Dispatches a specific prescription by review ID."""
    if current_user.role == "patient":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access forbidden: Patients cannot dispatch prescriptions."
        )
    review = db.query(PrescriptionReview).filter(PrescriptionReview.review_id == prescription_id).first()
    if not review:
        raise HTTPException(status_code=404, detail=f"Prescription {prescription_id} not found.")

    return deliver_prescription(
        DeliveryRequest(
            patient_id=review.patient_id,
            review_id=review.review_id,
            phone=phone,
            delivery_channel=channel
        ),
        db=db,
        current_user=current_user
    )

@prescriptions_router.patch("/{review_id}/archive", response_model=PrescriptionReviewResponse)
def archive_prescription_review(
    review_id: str,
    reason: str = Query(..., description="Mandatory clinical reason for archiving or voiding prescription"),
    target_status: str = Query("ARCHIVED", description="ARCHIVED, VOID, or INCORRECT"),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_roles(["doctor", "admin"]))
):
    """
    Controlled Archive / Void for E-Prescriptions:
    - Preserves clinical record for auditability
    - Enforces RBAC (Doctor or Admin)
    - Records archive reason, timestamp, and user
    - Patient record and other prescriptions remain intact
    - Logs audit event: PRESCRIPTION_ARCHIVED / PRESCRIPTION_VOIDED
    """
    review = db.query(PrescriptionReview).filter(PrescriptionReview.review_id == review_id).first()
    if not review:
        raise HTTPException(status_code=404, detail=f"Prescription {review_id} not found.")

    status_val = target_status.upper() if target_status.upper() in ["ARCHIVED", "VOID", "INCORRECT"] else "ARCHIVED"
    review.status = status_val
    review.archived_at = datetime.datetime.utcnow()
    review.archived_by = current_user.user_id
    review.archive_reason = reason.strip()
    db.commit()
    db.refresh(review)

    action_name = "PRESCRIPTION_VOIDED" if status_val == "VOID" else "PRESCRIPTION_ARCHIVED"
    log_audit_event(
        db,
        patient_id=review.patient_id,
        user_id=current_user.user_id,
        action=action_name,
        details=f"Prescription {review_id} marked {status_val} by {current_user.user_id}. Reason: {reason}"
    )

    return review

